# postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-postgre13-deploy
  labels:
    app: k8s-postgre13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-postgre13
  template:
    metadata:
      name: k8s-postgre13
      labels:
        app: k8s-postgre13
    spec:
      containers:
        - name: k8s-postgre13
          image: postgres:13-alpine3.20
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: postgre-pets-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgre-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb-script
      volumes:
        - name: postgre-storage
          emptyDir: {}
        - name: initdb-script
          configMap:
            name: pets-initdb-configmap

---
# nodejs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-nodejs-deploy
  labels:
    app: k8s-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-nodejs
  template:
    metadata:
      name: k8s-nodejs
      labels:
        app: k8s-nodejs
    spec:
      containers:
        - name: k8s-nodejs
          image: dangdang42/k8s-nodejs:v2
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DB_HOST
              value: k8s-postgre-svc
