# postgre
apiVersion: v1
kind: Service
metadata:
  name: k8s-postgre-svc
spec:
  selector:
    app: k8s-postgre13
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
# nodejs
apiVersion: v1
kind: Service
metadata:
  name: k8s-nodejs-svc
spec:
  selector:
    app: k8s-nodejs
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
